#!/bin/sh

. /etc/init.d/globals

case "$1" in
	start)
		SHOWINFO "Configuring network ... "
		ifup -a
	;;
	stop)
		SHOWINFO "Deconfiguring network ... "
		ifdown -a
	;;
	force-reload|restart)
		$0 stop
		$0 start
	;;
	*)
		echo "[$BASENAME] Usage: $0 {start|restart|force-reload|stop}"
	;;
esac
