#!/bin/sh

. /lib/mdev/common/log

case "$ACTION" in
	add|"")
		if [ -s /etc/wpa_supplicant.conf ]; then
			log_info "trying to bring $MDEV up"
			ifup $MDEV
		else
			log_warn "/etc/wpa_supplicant.conf missing or empty, not trying to bring $MDEV up"
		fi
		;;

	remove)
		log_info "trying to bring $MDEV down"
		ifdown $MDEV
		;;
esac
