#!/bin/sh

version_file=make/environment-image.mk
ver_major=$(date '+%Y')
ver_minor=$(date '+%m')

sed -i \
	-e "s|^IMAGE_VERSION_MAJOR =.*|IMAGE_VERSION_MAJOR = ${ver_major}|" \
	-e "s|^IMAGE_VERSION_MINOR =.*|IMAGE_VERSION_MINOR = ${ver_minor}|" \
	${version_file}

if ! git diff HEAD --quiet -- ${version_file}; then
	git add ${version_file}
	git commit -m "- ${version_file}: change version to ${ver_major}.${ver_minor}"
	git tag NI-${ver_major}.${ver_minor} $(git rev-parse HEAD)
	echo Version changed, will abort.
	echo Run \"git push\" again and run \"git push origin NI-${ver_major}.${ver_minor}\".
	exit 1
fi
