#!/bin/sh

. /etc/init.d/globals

case $1 in
	start)
		if [ -e /var/etc/.crond ]; then
			crond
		fi
	;;
	stop)
		trap "" INT
		kill -INT $(pidof crond)
	;;
	*)
		echo "[$BASENAME] Usage: $0 {start|stop}"
	;;
esac
