#!/bin/sh

case $1 in
	start)
		if [ ! -f /etc/hostname ]; then
			hwaddr=$(ifconfig eth0 | awk '/HWaddr/ { split($5,v,":"); print v[4] v[5] v[6] }')
			echo "NI-FLASH-${hwaddr}" > /etc/hostname
		fi

		hostname -F /etc/hostname
	;;
esac
