#!/bin/sh

case "$1" in
	start)
		/sbin/inetd
	;;
	stop)
		read pid < /var/run/inetd.pid || exit 1
		kill $pid
	;;
	reload)
		read pid < /var/run/inetd.pid || exit 1
		kill -HUP $pid
	;;
	restart)
		$0 stop
		$0 start
	;;
esac
