#!/bin/sh

# manage network interfaces and configure some networking options

case "$1" in
	start)
		echo -n "Configuring network interfaces... "
		ifup -a
		if type ifplugd >/dev/null 2>&1; then
			echo -n "Starting ifplugd... "
			ifplugd -F -p -q
		fi
		echo "done."
	;;
	stop)
		echo -n "Deconfiguring network interfaces... "
		ifdown -a
		if type ifplugd >/dev/null 2>&1; then
			echo -n "Killing ifplugd... "
			ifplugd -k
		fi
		echo "done."
	;;
	force-reload|restart)
		$0 stop
		$0 start
	;;
esac

exit 0
