#!/bin/sh

. /etc/init.d/globals

case "$1" in
	start)
		SHOWINFO "Configuring network ..."
		ifup -a
		if type ifplugd >/dev/null 2>&1; then
			SHOWINFO "Starting ifplugd ..."
			ifplugd -F -p -q
		fi
	;;
	stop)
		SHOWINFO "Deconfiguring network ..."
		ifdown -a
		if type ifplugd >/dev/null 2>&1; then
			SHOWINFO "Killing ifplugd ..."
			ifplugd -k
		fi
	;;
	force-reload|restart)
		$0 stop
		$0 start
	;;
	*)
		echo "[$BASENAME] Usage: $0 {start|restart|force-reload|stop}"
	;;
esac
