#
# makefile to build linux-drivers
#
# -----------------------------------------------------------------------------

HD6X_MALI_DRIVERS_VERSION = DX910-SW-99002-r7p0-00rel0
HD6X_MALI_DRIVERS_DIR = $(HD6X_MALI_DRIVERS_VERSION)
HD6X_MALI_DRIVERS_SOURCE = $(HD6X_MALI_DRIVERS_VERSION).tgz
HD6X_MALI_DRIVERS_SITE = https://developer.arm.com/-/media/Files/downloads/mali-drivers/kernel/mali-utgard-gpu

$(DL_DIR)/$(HD6X_MALI_DRIVERS_SOURCE):
	$(download) $(HD6X_MALI_DRIVERS_SITE)/$(HD6X_MALI_DRIVERS_SOURCE)

HD6X_MALI_DRIVERS_MAKE_VARS = \
	M=$(BUILD_DIR)/$(HD6X_MALI_DRIVERS_DIR)/driver/src/devicedrv/mali \
	EXTRA_CFLAGS="-DCONFIG_MALI_DVFS=y -DCONFIG_GPU_AVS_ENABLE=y" \
	CONFIG_MALI_SHARED_INTERRUPTS=y \
	CONFIG_MALI400=m \
	CONFIG_MALI450=y \
	CONFIG_MALI_DVFS=y \
	CONFIG_GPU_AVS_ENABLE=y

hd6x-mali-drivers: kernel-$(BOXTYPE) hd6x-libgles-headers $(DL_DIR)/$(HD6X_MALI_DRIVERS_SOURCE) | $(TARGET_DIR)
	$(START_BUILD)
	$(REMOVE)/$(HD6X_MALI_DRIVERS_DIR)
	$(UNTAR)/$(HD6X_MALI_DRIVERS_SOURCE)
	$(call APPLY_PATCHES,$(PKG_PATCHES_DIR))
	$(CHDIR)/$(HD6X_MALI_DRIVERS_DIR); \
		$(MAKE) -C $(KERNEL_OBJ_DIR) $(KERNEL_MAKE_VARS) $(HD6X_MALI_DRIVERS_MAKE_VARS); \
		$(MAKE) -C $(KERNEL_OBJ_DIR) $(KERNEL_MAKE_VARS) $(HD6X_MALI_DRIVERS_MAKE_VARS) INSTALL_MOD_PATH=$(TARGET_DIR) modules_install
	$(LINUX_RUN_DEPMOD)
	$(REMOVE)/$(HD6X_MALI_DRIVERS_DIR)
	$(TOUCH)
