#!/bin/sh

. /etc/init.d/functions
. /etc/init.d/globals

case $1 in
	start)
		if [ -e /proc/cpu/alignment ]; then
			echo -n "3" > /proc/cpu/alignment
		fi

		case "$(get_boxmodel)" in
			hd60|hd61)
				if [ -e /proc/stb/power/powerled2 ]; then
					echo off > /proc/stb/power/powerled2
				fi
			;;
			e4hd|protek4k)
				if [ -e /proc/stb/power/standbyled ]; then
					echo on > /proc/stb/power/standbyled
				fi
			;;
		esac
	;;
	*)
		echo "[$BASENAME] Usage: $0 {start}"
	;;
esac
